const MOCK_JOBS = [
    {
        id: "1",
        title: "Frontend Developer",
        company: "LINE MAN Wongnai",
        location: "Bangkok",
        type: "Full-time",
        salary: "50,000 – 90,000 ฿",
        description: "Build beautiful and performant web UIs for millions of users. Collaborate with product and design teams.",
        requiredSkills: ["React", "TypeScript", "CSS", "JavaScript"],
        preferredSkills: ["Next.js", "TailwindCSS", "GraphQL"],
        logo: "🟢",
    },
    {
        id: "2",
        title: "Backend Engineer (Node.js)",
        company: "Agoda",
        location: "Bangkok",
        type: "Full-time",
        salary: "80,000 – 150,000 ฿",
        description: "Design and maintain scalable microservices serving hundreds of millions of travel customers worldwide.",
        requiredSkills: ["Node.js", "TypeScript", "PostgreSQL", "Docker"],
        preferredSkills: ["Kafka", "Kubernetes", "Redis"],
        logo: "🔵",
    },
    {
        id: "3",
        title: "Full Stack Developer",
        company: "Bitkub",
        location: "Bangkok",
        type: "Full-time",
        salary: "70,000 – 120,000 ฿",
        description: "Work across frontend and backend to build crypto exchange features used by over 3 million users.",
        requiredSkills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
        preferredSkills: ["Web3.js", "Redis", "Docker"],
        logo: "🟡",
    },
    {
        id: "4",
        title: "Python Data Engineer",
        company: "Central Group",
        location: "Bangkok",
        type: "Full-time",
        salary: "60,000 – 100,000 ฿",
        description: "Build ETL pipelines and data platforms that power analytics for Thailand's largest retail group.",
        requiredSkills: ["Python", "SQL", "Apache Spark", "Airflow"],
        preferredSkills: ["BigQuery", "dbt", "Kafka"],
        logo: "🟠",
    },
    {
        id: "5",
        title: "DevOps / Cloud Engineer",
        company: "SCB Tech",
        location: "Bangkok",
        type: "Full-time",
        salary: "90,000 – 160,000 ฿",
        description: "Own the cloud infrastructure and CI/CD pipelines for SCB's digital banking products.",
        requiredSkills: ["AWS", "Docker", "Kubernetes", "Terraform"],
        preferredSkills: ["GitHub Actions", "Datadog", "Python"],
        logo: "🟣",
    },
    {
        id: "6",
        title: "React Native Developer",
        company: "Rabbit Finance",
        location: "Bangkok",
        type: "Full-time",
        salary: "55,000 – 95,000 ฿",
        description: "Develop and maintain cross-platform mobile apps for insurance and finance products.",
        requiredSkills: ["React Native", "JavaScript", "TypeScript", "REST APIs"],
        preferredSkills: ["Expo", "Firebase", "Redux"],
        logo: "🐰",
    },
    {
        id: "7",
        title: "Machine Learning Engineer",
        company: "KBTG (Kasikorn)",
        location: "Bangkok",
        type: "Full-time",
        salary: "100,000 – 180,000 ฿",
        description: "Build and deploy ML models for fraud detection, credit scoring, and customer recommendation.",
        requiredSkills: ["Python", "TensorFlow", "PyTorch", "SQL"],
        preferredSkills: ["MLflow", "Docker", "Kubernetes"],
        logo: "🏦",
    },
    {
        id: "8",
        title: "UI/UX Engineer",
        company: "Wongnai",
        location: "Bangkok",
        type: "Full-time",
        salary: "45,000 – 75,000 ฿",
        description: "Bridge design and engineering — translate Figma designs into pixel-perfect interactive components.",
        requiredSkills: ["React", "CSS", "Figma", "JavaScript"],
        preferredSkills: ["Storybook", "Framer Motion", "TailwindCSS"],
        logo: "🍴",
    },
    {
        id: "9",
        title: "Junior Backend Developer",
        company: "Pomelo Fashion",
        location: "Bangkok / Remote",
        type: "Full-time",
        salary: "30,000 – 55,000 ฿",
        description: "Great opportunity for new grads! Help build e-commerce backend APIs and learn from senior engineers.",
        requiredSkills: ["Node.js", "JavaScript", "REST APIs"],
        preferredSkills: ["TypeScript", "MySQL", "Docker"],
        logo: "👗",
    },
    {
        id: "10",
        title: "Cybersecurity Analyst",
        company: "DTAC (NTPLC)",
        location: "Bangkok",
        type: "Full-time",
        salary: "55,000 – 90,000 ฿",
        description: "Protect network infrastructure and respond to threats for Thailand's leading telecom company.",
        requiredSkills: ["Network Security", "Linux", "Python", "SIEM"],
        preferredSkills: ["CEH", "Splunk", "Wireshark"],
        logo: "🔐",
    },
    {
        id: "11",
        title: "iOS Developer (Swift)",
        company: "True Corporation",
        location: "Nonthaburi",
        type: "Full-time",
        salary: "60,000 – 110,000 ฿",
        description: "Build and release consumer iOS apps reaching millions in Thailand. SwiftUI experience is a plus.",
        requiredSkills: ["Swift", "Xcode", "UIKit", "REST APIs"],
        preferredSkills: ["SwiftUI", "CoreData", "Firebase"],
        logo: "📱",
    },
    {
        id: "12",
        title: "Go Backend Engineer",
        company: "Ascend Money (TrueMoney)",
        location: "Bangkok",
        type: "Full-time",
        salary: "90,000 – 160,000 ฿",
        description: "Build high-throughput payment and wallet services in Go for Southeast Asia's fintech leader.",
        requiredSkills: ["Go", "PostgreSQL", "gRPC", "Docker"],
        preferredSkills: ["Kafka", "Kubernetes", "Redis"],
        logo: "💸",
    },
    {
        id: "13",
        title: "Data Analyst",
        company: "Grab Thailand",
        location: "Bangkok",
        type: "Full-time",
        salary: "50,000 – 85,000 ฿",
        description: "Transform data into insights to influence product and operation decisions across Thailand.",
        requiredSkills: ["SQL", "Python", "Tableau", "Excel"],
        preferredSkills: ["BigQuery", "dbt", "Looker"],
        logo: "🚗",
    },
    {
        id: "14",
        title: "Site Reliability Engineer (SRE)",
        company: "ByteDance (TikTok)",
        location: "Bangkok / Hybrid",
        type: "Full-time",
        salary: "120,000 – 200,000 ฿",
        description: "Ensure reliability and scalability of TikTok infrastructure for millions of Thai users.",
        requiredSkills: ["Linux", "Python", "Kubernetes", "Prometheus"],
        preferredSkills: ["Go", "Terraform", "Grafana"],
        logo: "🎵",
    },
    {
        id: "15",
        title: "WordPress / PHP Developer",
        company: "PRTR Recruitment",
        location: "Bangkok / Remote",
        type: "Contract",
        salary: "30,000 – 50,000 ฿",
        description: "Develop and maintain WordPress websites and plugins for various Thai clients. Flexible hours.",
        requiredSkills: ["PHP", "WordPress", "MySQL", "JavaScript"],
        preferredSkills: ["CSS", "WooCommerce", "jQuery"],
        logo: "🌐",
    },
];
export default MOCK_JOBS;